name: Update data files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-data:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update data
        run: make update

      - name: Set up user
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Commit
        run: |
          if [ $(git status -s | wc -l) -gt 0 ]
          then
            git add static/data
            git commit -m "data: update"
            git push
            NEW_DATA=true
          else
            NEW_DATA=false
          fi
          echo "NEW_DATA=$NEW_DATA" >> $GITHUB_ENV
  deploy:
    if: ${{ env.NEW_DATA == 'true' }}
    uses: ./.github/workflows/deploy.yml
