name: Update data files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-data:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update data
        run: make update

      - name: Set up user
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Commit
        run: |
          git add static/data
          git commit -m "data: update" || exit 0
          git push
